apiVersion: v1
kind: Service
metadata:
  name: my-flask-app
  labels:
    app: my-flask-app
spec:
  type: ClusterIP
  selector:
    app: my-flask-app
  ports:
    - protocol: TCP
      port: 5000    
