apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
  labels:
    app: my-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    specs:
      container:
      - name: my-flask-app
        image: shizzyctrl/my-flask-app:latest 
        ports:
        - containerPort: 5000
        imagePullPolicy: Always  
